# Generated by Django 5.1.6 on 2025-02-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AddField(
            model_name='brand',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'HP'), ('B', 'DELL'), ('C', 'LENOVO'), ('D', 'ASUS')], max_length=1, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='tb_brand',
        ),
    ]
