# Generated by Django 5.1.6 on 2025-02-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_brand_tipo_prototype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prototype',
            options={'verbose_name': 'Modelos', 'verbose_name_plural': 'Modelo'},
        ),
        migrations.AddField(
            model_name='prototype',
            name='model',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='serial',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'DELL'), ('B', 'LENOVO'), ('C', 'HP'), ('D', 'ASUS'), ('E', 'OTROS')], max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
