# Generated by Django 5.1.6 on 2025-02-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent_id',
        ),
    ]
