# Generated by Django 5.1.6 on 2025-02-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_prototype_options_prototype_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(max_length=5000, null=True, unique=True, verbose_name='Código'),
        ),
    ]
