# Generated by Django 5.1.6 on 2025-02-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_brand_unique_together'),
        ('inventory', '0012_product_codigo'),
    ]

    operations = [
    ]
