# Generated by Django 5.1.6 on 2025-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='hard_drive',
        ),
        migrations.AlterField(
            model_name='hardware',
            name='memory',
            field=models.CharField(max_length=5000, verbose_name='Memoria'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='processor',
            field=models.CharField(max_length=5000, verbose_name='Procesador'),
        ),
    ]
