# Generated by Django 5.1.6 on 2025-02-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_hardware_hard_drive_alter_hardware_memory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='description',
        ),
    ]
