# Generated by Django 5.1.6 on 2025-02-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_hardware_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='tamanio',
            field=models.CharField(default='500GB', max_length=5000, verbose_name='GB'),
        ),
    ]
