# Generated by Django 5.1.6 on 2025-02-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_hardware_tamanio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='hardware',
            name='memory',
            field=models.CharField(max_length=5000, verbose_name='Memoria Ram'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='tamanio',
            field=models.CharField(max_length=5000, verbose_name='Tamaño de Disco'),
        ),
    ]
