# Generated by Django 5.1.6 on 2025-02-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_dateoperation_date_ipassignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateoperation',
            name='running_time',
            field=models.CharField(blank=True, choices=[('1-2', '1-2 Años'), ('2-3', '2-3 Años'), ('3-4', '3-4 Años'), ('4-5', '4-5 Años'), ('5+', '5+ Años')], max_length=10, null=True, verbose_name='Tiempo de funcionamiento'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='tipo_disco',
            field=models.CharField(choices=[('A', 'MECANICO'), ('B', 'SOLIDO'), ('B', 'NULO')], max_length=10, verbose_name='Tipo de Disco'),
        ),
    ]
